Edwin
zmazanv/FroilanFarm pull request #14
Opened 2023-05-17 20:51 UTC by ev3lasco

2023-05-17 20:55 UTC, zmazanv approved these changes
All looks good.

2023-05-17 21:17 UTC, chrisv0303 requested changes

2023-05-17 21:17 UTC, chrisv0303 commented on src/main/java/com/zipcodewilmington/froilansfarm/classes/Tractor.java
> -    public void harvest (Farm farm) {}
Just change your parameter into Crop crop. In the instructions, Tractor harvest a Crop instead of doing Farm. Also, just keep the space together between harvest and (. But overall, looks good.

2023-05-18 01:56 UTC, zmazanv approved these changes
Looks fine.

2023-05-18 02:05 UTC, merged